name: Node.js CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.1'
        npm-version: '10.5.2'

    - name: Navigate to Xenon Page folder
      run: cd "Xenon Page"

    - name: Install dependencies
      run: npm install
      working-directory: "Xenon Page"

    - name: Commit changes
      run: |
        git config --global user.email "Dino_doge@qq.com"
        git config --global user.name "KirsminX"
        git add -A
        git diff-index --quiet HEAD || git commit -m "Update dependencies"
        git push