name: Install npm dependencies and upload changes

on:
  push:
    branches:
      - main

jobs:
  install-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '21.7.1'
        npm-version: '10.5.2'

    - name: Install npm dependencies
      run: |
        cd "Xenon Page"
        npm install

    - name: Upload changes
      uses: actions/upload-artifact@v2
      with:
        name: xenon-page-changes
        path: Xenon\ Page/node_modules  # 上传安装的依赖

  download-and-restore:
    needs: install-and-upload
    runs-on: ubuntu-latest

    steps:
    - name: Download changes
      uses: actions/download-artifact@v2
      with:
        name: xenon-page-changes

    - name: Restore changes
      run: |
        mv xenon-page-changes/node_modules "Xenon Page/node_modules"