name: Install and Commit Dependencies

on:
  push:
    branches:
      - main

jobs:
  install_and_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21.7.1'
        npm-version: '10.5.2'

    - name: Install NPM Dependencies
      run: |
        cd "Xenon Page"
        npm install

    - name: Commit Changes
      run: |
        git config --global user.email "Dino_doge@qq.com"
        git config --global user.name "KirsminX"
        git add -A
        git diff --cached --exit-code || git commit -m "Update dependencies"
        git push