name: Install Node.js and npm

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '21'

    - name: Navigate to Xenon Page directory
      run: cd 'Xenon Page'

    - name: Install npm dependencies
      run: npm install