name: Install NPM Packages  
  
on:  
  push:  
    branches: [ main ]  
  pull_request:  
    branches: [ main ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  
  
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.7.1'
  
      - name: Install NPM packages  
        working_directory: Xenon Page
        run: npm install